### ISSUE TITLE
Top button in top-menu homepage

### ISSUE THREAD

**Issue by Socioneers** [kgish/discourse-pvda-plugin#55]
Top in the top menu does not show up on homepage. Is it possible to have this button in the menu?

<img width="847" alt="screen shot 2016-12-16 at 12 15 54" src="https://cloud.githubusercontent.com/assets/11832800/21261087/9e574de6-c389-11e6-9d76-8ad4cad2a1ab.png">
<img width="959" alt="screen shot 2016-12-16 at 12 16 05" src="https://cloud.githubusercontent.com/assets/11832800/21261086/9e5759a8-c389-11e6-86f6-1d33aea232f5.png">

**Comment by kgish** [comment]
I will check into this.

**Comment by kgish** [comment]
For some reason, if my memory serves me right, long ago it was decided that `top` should not be visible. That's why it was coded into the blacklist. Removed it from the list. Now, only `categories` is removed.

A bit confusing, would think that using the admin settings would be the right place to do all of this and not in the code. Maybe there was originally some specific reason for doing it this way, don't know.
